[phases.setup]
nixPkgs = [
    "php82",
    "php82Packages.composer"  # Nome exato do pacote Composer para PHP 8.2
]

[phases.build]
commands = [
    # Cria o Laravel em uma pasta temporária
    "composer create-project laravel/laravel tmp-laravel --no-interaction",
    
    # Move seus arquivos para a estrutura do Laravel
    "mv app tmp-laravel/app",
    "mv database tmp-laravel/database",
    "mv composer.json tmp-laravel/composer.json",
    
    # Define a pasta temporária como a raiz do projeto
    "mv tmp-laravel/* .",
    "rm -rf tmp-laravel",
    
    # Instala dependências
    "composer install --ignore-platform-reqs --no-dev --optimize-autoloader",
    
    # Executa migrations
    "php artisan migrate --force"
]

[start]
command = "php artisan serve --host=0.0.0.0 --port=${PORT}"