[phases.setup]
nixPkgs = ["php82", "composer"]

[phases.build]
commands = [
    "composer install --ignore-platform-reqs --no-dev --optimize-autoloader",
    "php artisan migrate --force"
]

[start]
command = "php artisan serve --host=0.0.0.0 --port=${PORT}"