[phases.setup]
nixPkgs = [
    "php82",
    "php83Extensions.pdo",
    "php83Extensions.mbstring",
    "php83Extensions.openssl",
    "php83Extensions.json",
    "php83Extensions.gd",         # Necessário para o Filament
    "php83Extensions.fileinfo",   # Necessário para o Laravel
    "mysql57"                     # Cliente MySQL para migrations
]

[phases.build]
commands = [
    "composer install --ignore-platform-reqs --no-dev --optimize-autoloader",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan migrate --force"
]

[start]
command = "php artisan serve --host=0.0.0.0 --port=${PORT}"